/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MultiPlayer_BackThread */

#ifndef _Included_com_example_androidex_MultiPlayer_BackThread
#define _Included_com_example_androidex_MultiPlayer_BackThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_androidex_MultiPlayer_BackThread_MIN_PRIORITY
#define com_example_androidex_MultiPlayer_BackThread_MIN_PRIORITY 1L
#undef com_example_androidex_MultiPlayer_BackThread_NORM_PRIORITY
#define com_example_androidex_MultiPlayer_BackThread_NORM_PRIORITY 5L
#undef com_example_androidex_MultiPlayer_BackThread_MAX_PRIORITY
#define com_example_androidex_MultiPlayer_BackThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
