/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MultiPlayer_Player */

#ifndef _Included_com_example_androidex_MultiPlayer_Player
#define _Included_com_example_androidex_MultiPlayer_Player
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
