/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidex_MultiPlayer */

#ifndef _Included_com_example_androidex_MultiPlayer
#define _Included_com_example_androidex_MultiPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidex_MultiPlayer
 * Method:    readjni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_androidex_MultiPlayer_readjni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
